image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: ignore

tasks:
  - name: docker-daemon
    before: sudo docker-up

  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'
